version: '3.7'

services:
  metabase:
    image: metabase/metabase:latest
    depends_on:
      - traefik
      - db
    restart: always
    ports:
      - 3000:3000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.node-server.rule=Host(`meta.layziking.xyz`)'
      - 'traefik.http.routers.node-server.entrypoints=websecure'
      - 'traefik.http.routers.node-server.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'

    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabasepass%w3rd
      - MB_DB_HOST=db

  
  traefik:
    image: traefik:v2.4 
    container_name: 'traefik'
    command:
      - '--api.insecure=true'
      - '--api.dashboard=true'
      - '--api.debug=true'
      - '--providers.docker=true'
      - '--log.LEVEL=DEBUG'
      - '--entryPoints.web.address=:80'
      - '--entryPoints.websecure.address=:443'
      - '--providers.docker.exposedbydefault=false'
      - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.myresolver.acme.email=nonso@bitnob.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '443:443'
      - '80:80'
      - '8080:8080'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'


  db:
    image: postgres
    container_name: postgresql_metabase
    environment:
      - POSTGRESQL_DATABASE=metabase
      - POSTGRESQL_USER=metabase
      - POSTGRESQL_PASSWORD=metabasepass%w3rd
    ports:
      - 5432:5432

    volumes:
      - db_data:/var/lib/postgresql/data



volumes:
  db_data: