version: "3.8"
services:
  metabase:
    image: metabase/metabase:latest
    depends_on:
      - traefik
    restart: always
    ports:
      - 3000:3000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.node-server.rule=Host(`meta.layziking.xyz`)'
      - 'traefik.http.routers.node-server.entrypoints=websecure'
      - 'traefik.http.routers.node-server.tls.certresolver=myresolver'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)'
      - 'traefik.http.routers.redirs.entrypoints=web'
      - 'traefik.http.routers.redirs.middlewares=redirect-to-https'

  
  traefik:
    image: traefik:v2.4 
    container_name: 'traefik'
    command:
      - '--api.insecure=true'
      - '--api.dashboard=true'
      - '--api.debug=true'
      - '--providers.docker=true'
      - '--log.LEVEL=DEBUG'
      - '--entryPoints.web.address=:80'
      - '--entryPoints.websecure.address=:443'
      - '--providers.docker.exposedbydefault=false'
      - '--certificatesresolvers.myresolver.acme.httpchallenge=true'
      - '--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web'
      - '--certificatesresolvers.myresolver.acme.email=nonso@bitnob.com'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
    ports:
      - '443:443'
      - '80:80'
      - '8080:8080'
    volumes:
      - './letsencrypt:/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'